export const SET_DATA = "SET_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_QUANTITY_IN_CART = "UPDATE_QUANTITY_IN_CART";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
export const UPDATE_TOTAL_QUANTITY="UPDATE_TOTAL_QUANTITY";
export const UPDATE_SEARCH_ITEMS = "UPDATE_SEARCH_ITEMS";
// export const UPDATE_TOTAL_QUANTITY_IN_CART = "UPDATE_TOTAL_QUANTITY_IN_CART";